root = "." 
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ./cmd/server"
  bin = "tmp/main"
  full_bin = "tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_ext = ["md"]